### ISSUE TITLE
Allow to specify endpoint_url

### ISSUE THREAD

**Issue by GillesMocellin** [angeloc/s3-pit-restore#11]
For those who use other implementations like Ceph Rados Gateway, we need to set another endpoint.
AWS CLI and its config file does still not allow that :
https://github.com/aws/aws-cli/issues/1270

So the program should pass that argument to the boto3.client method.

**Comment by angeloc** [comment]
@GillesMocellin could you elaborate more?

**Comment by GillesMocellin** [comment]
Of course, simple : I'd like to use this script, but not with AWS S3, but with my own Ceph clueter, exposing Object Storage via S3 protocol with its Rados Gateway component.
Others could want to use this script with other storage systems using the S3 protocol (Minio, Dell ECS...)

So the only thing we need is a --endpoint option or --url, where we can override the https://s3.amazonaws.com endpoint with another.

If the script use the boto3 module, which use the aws config files, it cannot get the endpoint info, because that option still doe not exist.
So an additional parameter is needed.

See here some ways to do : 
https://stackoverflow.com/questions/32618216/overwrite-s3-endpoint-using-boto3-configuration-file

**Comment by angeloc** [comment]
@GillesMocellin : clear now! Would you mind opening a PR?
