### ISSUE TITLE
Replacement for a backup tool?

### ISSUE THREAD

**Issue by binaryfire** [angeloc/s3-pit-restore#17]
Hi guys,

Great project! Sorry to post a question here, but I was wondering if this + rclone could be a viable backup solution? We're currently doing incremental backups to a S3 bucket via duplicati. But if this can reliably restore to a point in time, it seems like much cleaner solution.

Are there any issues with large numbers of files, file sizes etc? Or anything else that would make it unsuitable for backups?

Cheers

**Comment by angeloc** [comment]
Please try and let us know your findings!
