### ISSUE TITLE
Restore from s3 bucket to s3 bucket in different account

### ISSUE THREAD

**Issue by Heiko-san** [angeloc/s3-pit-restore#9]
Hi,

is there a way to authenticate to 2 different accounts or to 1 account using 2 different assume roles, thus is there a way to restore a s3 bucket to a target s3 bucket in a different account (directly, without a stopover like sync to local, then sync to target bucket)?

**Comment by angeloc** [comment]
s3-pit-restore uses boto3 behind the scenes. I don't think boto3 supports a multiple authentication mechanism, so I think it's not possible.

**Comment by Stivens73** [comment]
If you use Role Based Access on AWS (create a role in console and allow it inside of certain vpc), then you might not need to manage credentials from boto or envs on the machine itself
